service: clarifi-api


provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: default

plugins:
  - 'serverless-plugin-typescript'
  - serverless-plugin-optimize
  - serverless-offline

package:
  individually: true
  include:
    - apps/src/api/**
  exclude:
    - '**'

functions:
  index:
    handler: apps/src/api/main.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
