service: clarifi-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: personal
  stage: ${opt:stage, 'dev'}

plugins:
  - serverless-single-page-app-plugin
  - serverless-deployment-bucket
  - serverless-layers

package:
  individually: true
  include:
    - dist/apps/api/**
  exclude:
    - '**'
  excludeDevDependencies: true

custom:
  s3LocalPath: dist/apps/clarifi
  deploymentBucket:
    name: clarifi-layers
    versioning: false
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: ${self:provider.stage}

  serverless-layers:
    - index:
        functions:
          - index
        layersDeploymentBucket: clarifi-layers
        dependenciesPath: dist/apps/api/package.json

functions:
  index:
    handler: dist/apps/api/main.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any

resources:
  Resources:
    # Angular app
    WebAppS3Bucket: ${file(resources/frontend/webapp-bucket.yml)}
    WebAppS3BucketPolicy: ${file(resources/frontend/webapp-bucket-policy.yml)}
    WebAppCloudFrontDistribution: ${file(resources/frontend/webapp-bucket-cloudfront.yml)}

    # RDS Username / Password
    DBSecret: ${file(resources/rds/db-secret.yml)}

    # RDS Database
    #RDSDatabase: ${file(resources/rds/aurora-mysql.yml)}


  ## In order to print out the hosted domain via `serverless info` we need to define the DomainName output for CloudFormation
  Outputs:
    WebAppS3BucketOutput:
      Value:
        'Ref': WebAppS3Bucket
    WebAppCloudFrontDistributionOutput:
      Value:
        'Fn::GetAtt': [ WebAppCloudFrontDistribution, DomainName ]
