service: clarifi-api


provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: default

package:
  individually: true
  include:
    - dist/apps/api/**
  exclude:
    - '**'

functions:
  index:
    handler: dist/apps/api/main.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
