service: clarifi-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  deploymentBucket:
    name: clarifi-deployment
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:PutObject
        - s3:GetObject
      Resource: "*"


plugins:
  - serverless-deployment-bucket
  - serverless-layers

package:
  individually: true
  include:
    - dist/apps/api/**
  exclude:
    - '**'



custom:
  prune:
    automatic: true
    number: 3
  serverless-layers:
    dependenciesPath: dist/apps/api/package.json


functions:
  index:
    handler: dist/apps/api/main.handler
    events:
    - http:
        cors: true
        path: '/'
        method: any
    - http:
        cors: true
        path: '{proxy+}'
        method: any
