service: clarifi-api

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  profile: personal
  environment:
    API_URL: { "Fn::Join" : ["", [" https://", { "Ref" : "ApiGatewayRestApi" }, ".execute-api.${self:provider.region}.amazonaws.com/${self:provider.stage}" ] ]  }

plugins:
  - serverless-single-page-app-plugin
  - serverless-deployment-bucket
  - serverless-layers

package:
  individually: true
  include:
    - dist/apps/api/**
  exclude:
    - '**'

custom:
  s3LocalPath: dist/apps/clarifi
  deploymentBucket:
    name: clarifi-layers
    versioning: false
    accelerate: true
    blockPublicAccess: true
    tags:
      - Key: Environment
        Value: ${opt:stage, 'dev'}

  serverless-layers:
    - index:
        functions:
          - index
        layersDeploymentBucket: clarifi-layers
        dependenciesPath: dist/apps/api/package.json

functions:
  index:
    handler: dist/apps/api/main.handler
    events:
      - http:
          cors: true
          path: '/'
          method: any
      - http:
          cors: true
          path: '{proxy+}'
          method: any

resources:
  Resources:
    WebAppS3Bucket: ${file(resources/clarifi/webapp-bucket.yml)}
    WebAppS3BucketPolicy: ${file(resources/clarifi/webapp-bucket-policy.yml)}
    WebAppCloudFrontDistribution: ${file(resources/clarifi/webapp-bucket-cloudfront.yml)}

  ## In order to print out the hosted domain via `serverless info` we need to define the DomainName output for CloudFormation
  Outputs:
    WebAppS3BucketOutput:
      Value:
        'Ref': WebAppS3Bucket
    WebAppCloudFrontDistributionOutput:
      Value:
        'Fn::GetAtt': [ WebAppCloudFrontDistribution, DomainName ]
